### ISSUE TITLE
Z Steppers Auto-Alignment (G34)

### ISSUE THREAD

**Issue by iiKelZenii** [scmanjarrez/OctoPrint-SmartABL#11]
### Describe the solution you'd like

Please can your add  "Z Steppers Auto-Alignment" feature support?
I have dual Z axis motor, and after power off Z steppers, or power off printer, Z axis can move down. I wold like to use "Z Steppers Auto-Alignment" marlin feature to fix this problem before bed leveling.
Or may be can your add custom G-code edit menu for bed leveling? Not a single command. 
Thanks.

**Comment by scmanjarrez** [comment]
How does it work? You send G34 and then G29? I can make the custom gcode to receive a list of gcodes instead, is that ok?

**Comment by iiKelZenii** [comment]
> How does it work? You send G34 and then G29?

I send G28 then G34 and then G29. 

> I can make the custom gcode to receive a list of gcodes instead, is that ok?

Yes, I think it would be great.

**Comment by scmanjarrez** [comment]
Ok, I'll add that asap, thanks!

**Comment by scmanjarrez** [comment]
Released on 0.5.0

**Comment by iiKelZenii** [comment]
I test it. Works fine for me. Thanks.
