### ISSUE TITLE
M420 S1 and then print just stalls

### ISSUE THREAD

**Issue by tkunchick** [scmanjarrez/OctoPrint-SmartABL#13]
### The problem

I don't know if I have something configured wrong or not. but since last update, when trying to print with unrestricted able with unified bed leveling, watching terminal, when I start a print, I see it go through the motions, once it hits abl, in this case, g29 p1, instead it runs M420 S1, and then just stops

### Version of SmartABL

SmartABL (0.5.1)

### Version of OctoPrint

 OctoPrint 1.8.7 

### Operating system running OctoPrint

OctoPrint 1.8.7 Python 3.9.2 OctoPi 1.0.0

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

**Comment by tkunchick** [comment]
disabling plugin allows print to process normally.

**Comment by scmanjarrez** [comment]
Can you upload your plugin_SmartABL.log? Also, this behavior only occurs when using ABL buttons?

**Comment by scmanjarrez** [comment]
Also, a screenshot of your settings if possible.

**Comment by tkunchick** [comment]
The log file is a 0 byte file currently. should I set debug level on the log? Sorry if I don't understand, never been much on the programming side of IT. Current print has 3-4 hours so any changes will take at least that long.
<img width="351" alt="Screenshot 2023-04-01 at 2 54 01 PM" src="https://user-images.githubusercontent.com/45150915/229309171-cd70c802-3d53-4f31-b562-154203780a24.png">


As far as settings, I normally run both printers on 5 prints or bed temp change. though I recently changed that one jus on the main screen to always run ABL due to the bed being warped/skewed and any time I move I remove the glass it changes the level.  
<img width="710" alt="Screenshot 2023-04-01 at 2 52 30 PM" src="https://user-images.githubusercontent.com/45150915/229309107-c0b02a2f-dcf1-4087-a111-6dae9870a7b3.png">

**Comment by scmanjarrez** [comment]
Yes, you need to enable debugging under settings -> logging, then set SmartABL to DEBUG. Can you share your starting gcode? I can do my own tests using your starting gcode using the config presented in the screenshot

**Comment by tkunchick** [comment]
[start.txt](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/11130367/start.txt)
Had it on my desktop after watching the m420 go by in terminal wondering where the heck it came from :-)

that was ugly.

**Comment by tkunchick** [comment]
Watching the terminal, it would hit the m420 s, report a valid mesh, then just sit there until the heaters timed out.

**Comment by scmanjarrez** [comment]
That's really weird, I fixed that problem in version 0.5.1... but I think I missed a case. I'll look into that. Thank you

**Comment by tkunchick** [comment]
No worries. Pretty sure I had the same issue yesterday with my Neo v2 that I was upgrading the firmware to MRiscoC. I edit it a bit, so assumed I screwed up and just put the Creality firmware back on so I could get a couple prints done. 


If so, then its just UBL and not the standard.. Assume Creality is using Linear.

**Comment by scmanjarrez** [comment]
Ok, I found the cause. I definitely forgot about the buttons when I added the new algorithm 😅.
Edit: Oh, I didn't even know about multiple G29... that could be a case to note.

**Comment by tkunchick** [comment]
Like I said, I assume user error, myself, first. when I started to see the issue on the E3V2, and remembered they both updated.. that's when I came here. All Good. :)

**Comment by scmanjarrez** [comment]
Can you explain how unified ABL works? Whats the meaning of the P (phase I guess?)

**Comment by tkunchick** [comment]
I don't totally understand it, pretty sure I copied and pasted from 

https://github.com/mriscoc/Ender3V2S1/wiki/Slicer-G-code-Scripts

https://marlinfw.org/docs/gcode/G029-ubl.html


P1: Automatic Probing invalidates the mesh and continues automatic probing using the probe.
In most cases the probe can’t reach all areas that the nozzle can due to the offsets specified by X_PROBE_OFFSET_FROM_EXTRUDER and Y_PROBE_OFFSET_FROM_EXTRUDER. Deltabots can only probe within the area where DELTA_PROBEABLE_RADIUS and DELTA_PRINTABLE_RADIUS overlap.
Unreachable points can be filled in later with the P2 and P3 phases.
Use C to leave the previous mesh intact and automatically probe needed points. This allows you to invalidate parts of the mesh but still use Automatic Probing.
The X and Y parameters prioritize where to try and measure points. If omitted, the current probe position is used.
Use T (Topology) in this phase to report the probing results.
P1 will suspend mesh generation if the controller button is held down. Note that you may need to press and hold the switch for several seconds if moves are underway.

**Comment by tkunchick** [comment]
I should mention, I didn't touch a 3d printer until January this year. still wrapping my head around it all. Been in IT for nearly 30 years though.

**Comment by scmanjarrez** [comment]
I think I'll need the logs. I've been testing it with and without restricted ABL, but it seems to work as expected. Do you have, by any chance, the output from M420 V1? I think SmartABL isn't detecting if mesh is valid/invalid, so it doesn't continue the print (which I'd need to fix)

**Comment by tkunchick** [comment]
I didn't think to save it. I will get it to you in a few hours once the current print finishes.

**Comment by scmanjarrez** [comment]
This version should (I hope) fix the print stopping after M420 https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/0.5.2rc0

**Comment by tkunchick** [comment]
Well.. I thought I had uninstalled it, but I only disabled it, but I reinstalled, and it got the new 5.2 version. at any rate, it does work.

Is there a way I can re-install the earlier version? or are you sure you got what you needed already?

**Comment by scmanjarrez** [comment]
I think it should "work". I haven't studied yet the unified ABL. For the time being, at least it doesn't get stuck. When you finish your print, can you give me the logs of 0.5.1? (You should be able to install the old version using the link https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/0.5.1) or using the package manager (i haven't released 0.5.2 yet, so 0.5.1 should be the one being installed)

**Comment by tkunchick** [comment]
Here is the log and info from terminal. It did just stall again after getting mesh.

Wondering if its just the repeated G29 codes with different syntax.

But really, with the ABL button toggled to always, why change anything?

Also wondering, if abl was set to on, is it possible to just allow the gcode call to pass rather than replacing it with a different command?

As I understand it, 

(cut and pasted from somewhere and in my machine start code for slicer)
G29 P1    ; automatically populate mesh with all reachable points
G29 P3    ; infer the rest of the mesh values
G29 P3    ; infer the rest of the mesh values again


G29 P1 forces a new mesh..
G29 P3 forces it to fill in any gaps and make the mathematical adjustments between known points..

again, as I understand it.

[plugin_SmartABL.log](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/11130707/plugin_SmartABL.log)
[abl stall.txt](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/11130708/abl.stall.txt)

**Comment by scmanjarrez** [comment]
I'll think about it. Also, your logs are very helpful, I now know why isn't detecting your valid/invalid mesh.

**Comment by tkunchick** [comment]
Glad I could help with your work. I really like it on my Neo that still has a flat bed and rarely changes. once I get around to replacing the bed and glass (both are warped) on my E3V2, will be using it on both my machines again. save a lot of time and frustration waiting for it to do something I know is good haha.

👍 Thank you for all your work.

**Comment by scmanjarrez** [comment]
Hi, can you check this version? https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/0.5.2rc1 This version should take into account UBL.

**Comment by piebaker** [comment]
Had the same issue, M240 S0. 0.5.2rc1 fixed it right up. However it also seems SABL may also be sending an erroneous G81 command. I've had to block it on my end to prevent it locking up the printer. I'm using a prusa mini, but that uses G29, which it did use after i blocked G81. Very odd

**Comment by scmanjarrez** [comment]
Can you upload plugin_SmartABL.logs? I'm taking into account G80 (for abl) and G81 (to check current mesh state) for prusa, I didn't know there was another prusa firmware that used G29.

**Comment by piebaker** [comment]
> Can you upload plugin_SmartABL.logs? I'm taking into account G80 (for abl) and G81 (to check current mesh state) for prusa, I didn't know there was another prusa firmware that used G29.

[plugin_SmartABL.log](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/11145493/plugin_SmartABL.log)

So a good example can be found [here.](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/blob/master/wiki/gcode-examples.md) While the prusa mini is a prusa machine, it uses the usual G28/29 process as opposed to G80/G81. It's strange as this was working correctly prior to this update.

**Comment by scmanjarrez** [comment]
I changed the algorithm to fix another error, but it ended having its own issues

**Comment by scmanjarrez** [comment]
> > Can you upload plugin_SmartABL.logs? I'm taking into account G80 (for abl) and G81 (to check current mesh state) for prusa, I didn't know there was another prusa firmware that used G29.
> 
> [plugin_SmartABL.log](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/11145493/plugin_SmartABL.log)
> 
> So a good example can be found [here.](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/blob/master/wiki/gcode-examples.md?rgh-link-date=2023-04-04T06%3A52%3A15Z) While the prusa mini is a prusa machine, it uses the usual G28/29 process as opposed to G80/G81. It's strange as this was working correctly prior to this update.

I see, I'll release a new version adding prusa mini to the list of firmwares. Thank you!

**Comment by scmanjarrez** [comment]
@piebaker do you know if prusa buddy have eeprom enabled? are you able to save mesh with M500?

**Comment by piebaker** [comment]
> @piebaker do you know if prusa buddy have eeprom enabled? are you able to save mesh with M500?

No as far as I am aware M500 is disabled unfortunately. Enabling it requires physically breaking a part on the buddyboard, installing custom firmware, and voiding the warranty

**Comment by scmanjarrez** [comment]
Hey @piebaker, can you check this version? https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/1.0.0rc0 It should detect prusa-buddy.

**Comment by piebaker** [comment]
> Hey @piebaker, can you check this version? [`1.0.0rc0` (release)](https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/1.0.0rc0) It should detect prusa-buddy.

Yup, looks like that works A-OK. Thanks so much!

**Comment by scmanjarrez** [comment]
Released on https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/1.0.0
