### ISSUE TITLE
SmartABL continually executes ABL on every print if ABL not saved to EEPROM

### ISSUE THREAD

**Issue by AndyShap2020** [scmanjarrez/OctoPrint-SmartABL#15]
### The problem

Hi Sergio,  the add-in works really well! I've noticed an issue that may not be a bug.  When SmartABL triggers an ABL, it will run and on the actual printer screen, you have a prompt to save the newly run ABL. If you don't press save, then the print job starts. But on the next print job, SmartABL runs again. I guess this makes sense, since the ABL Mesh was not saved to EEPROM.  Is there a way for SmartABL to execute the save automatically, as opposed to me needing to manually press SAVE on the printer screen?

### Version of SmartABL

1.0.0

### Version of OctoPrint

1.87

### Operating system running OctoPrint

Version 0.18.0, running on Raspberry Pi 3 Model B Rev 1.2

### Printer model & used firmware incl. version

Ender 3v2, Mriscoc 2.13

### Browser and version of browser, operating system running browser

Firefox, Windows 10 Pro 22H2

### Checklist of files to include below

- [X] Systeminfo Bundle (always include!)
- [ ] Contents of the JavaScript browser console (always include in cases of issues with the user interface)
- [ ] Screenshots and/or videos showing the problem (always include in case of issues with the user interface)
- [ ] GCODE file with which to reproduce (always include in case of issues with GCODE analysis or printing behaviour)

### Additional information & file uploads

[plugin_SmartABL.log](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/11327076/plugin_SmartABL.log)

**Comment by scmanjarrez** [comment]
Hi, thanks for reporting it. Can you share your start gcode? I suspect the problem is M420 S1 Z2; I need to confirm it and see how to fix it.

**Comment by AndyShap2020** [comment]
; Ender 3 Custom Start G-code
G92 E0 ; Reset Extruder

​;------------------------------------------
;*** Start Dual Nozzle/Bed Preheating ***
;M140 S{material_bed_temperature_layer_0} ; start preheating the bed
;M104 S{material_print_temperature_layer_0} ﻿T0 ; start preheating hotend

G28 ; home
;G29 ; Run Auto Bed Level on every print
M420 S1 Z2; Use Level Mesh up to 2mm;

M190 S{material_bed_temperature_layer_0} ; heat to Cura Bed setting
M109 S{material_print_temperature_layer_0} ﻿T0 ; heat to Cura Hotend
;*** End Preheating ***

;*** Signal Print Start Tone
M300 S1000 P500 ; chirp to indicate starting to print
;*** End Single Start Tone

G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X0.1 Y20 Z0.3 F5000.0 ; Move to start position
G1 X0.1 Y200.0 Z0.3 F1500.0 E15 ; Draw the first line
G1 X0.4 Y200.0 Z0.3 F5000.0 ; Move to side a little
G1 X0.4 Y20 Z0.3 F1500.0 E30 ; Draw the second line
G92 E0 ; Reset Extruder
G1 Z2.0 F3000 ; Move Z Axis up little to prevent scratching of Heat Bed
G1 X5 Y20 Z0.3 F5000.0 ; Move over to prevent blob squish

**Comment by scmanjarrez** [comment]
Oh, I see the problem. This option was on early versions of SmartABL, but after the algorithm update, I removed it (unintentionally). Can you check this pre-release? https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/1.1.0rc0. It should work as previous releases (save to eeprom on marlin firmware)

**Comment by AndyShap2020** [comment]
Not quite there, it did an ABL TWICE in a row and still left the screen at Save\Continue

**Comment by scmanjarrez** [comment]
What do you mean by Save/continue? I don't have anything related with that in the plugin. Can you send your logs again and a screenshot of your LCD?

**Comment by AndyShap2020** [comment]
I’ll get that to you in a bit. I am at 1/5 right now.

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by AndyShap2020** [comment]
Two issues:
1. As of this particular version it now runs an ABL and then immediately runs a second ABL .  
2. Didn't fix the screen popping up with Save/Continue.  While this screen is up, the printer has gone on to the next Gcode of warming up the hotend.  If it gets to temperature, it will start the print. But because I didn't click on SAVE, it will run an ABL on the next print. If I don't click SAVE on THAT print, it will run an ABL on the next print as well.
(This means that the Octoprint ABL starts between the GCode line of M190 and M109, refer to the start code above)
![DSC00655](https://user-images.githubusercontent.com/71109919/235271343-9c53b1ac-cd99-41a0-a98b-9add8af0f2b2.JPG)
[plugin_SmartABL.log](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/11357914/plugin_SmartABL.log)

**Comment by scmanjarrez** [comment]
I don't think I can't do anything about that screen, it's from your firmware. Normal LCD screen doesn't show that dialog. Have you checked how it works? Does it pop up when you run G29?

**Comment by AndyShap2020** [comment]
Yes, it does.   Not a huge deal, but you might want to make a note that for anyone using MRISCOC firmware for Ender 3v2, they need to press save, or else the ABL will not be written to EEPROM.

I am going to go back to the previous version so I can get rid of the double ABL.

THANKS!!

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by scmanjarrez** [comment]
I'll fix that, I've realized what's the problem. Does M500 work with MRISCOC firmware? I can see the M500 gcode being sent, but I don't know if the mesh is actually saved.

**Comment by AndyShap2020** [comment]
I don’t know. I’ll post a question to the Facebook group.  Are you familiar with MRISCOC’s firmaware?  Jyer’s is no longer supported and MRISCOC is fantastic.

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by scmanjarrez** [comment]
No... I'm currently using Klipper (also, I have LCD12864)

**Comment by scmanjarrez** [comment]
This version should fix multiple triggers: https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/1.1.0rc1. I'll check MRISCOC firmware if we can force save or at least avoid the viewer

**Comment by AndyShap2020** [comment]
I've spoken with MRISCOC,  the G code: C108 cancels the screen waiting for confirmation.  The software DOES recognize M500, so the screen shouldn't need to be there. How do we incorporate the C108 command to run after the ABL finishes?  Would that go in the middle line for custom codes?

https://github.com/mriscoc/Ender3V2S1/wiki/Custom-C-gcodes

**Comment by scmanjarrez** [comment]
~~I'm not really sure, try with G29, C108 or G29, C108.~~
Yeah, mriscoc confirmed my answer on reddit. G29, C108

**Comment by scmanjarrez** [comment]
Hey Andy, have you been able to test the latest pre-release? Does it still trigger multiple ABL? Were you able to skip mesh viewer screen?

**Comment by AndyShap2020** [comment]
I think I did install it already (I’ve been running lots of prints, so not sure).  If I look at the plugin, should it say rc1, etc? Mine just says 1.1.0

I’ll reinstall after my next print. I will also add the other codes.

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by scmanjarrez** [comment]
It's named the same. Thank you

**Comment by AndyShap2020** [comment]
Something is wrong. I am currently on print 7/5??  It should have done an ABL the next print after 5/5.

Rc1 is installed at this point.

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by scmanjarrez** [comment]
Can you upload the log file?

**Comment by AndyShap2020** [comment]
I'm currently on print 9/5.  P.S. I think I added this after the install of 1.1.0rc1 as well:  Trigger Custom Codes: G29,M500,C108

[plugin_SmartABL.log](https://github.com/scmanjarrez/OctoPrint-SmartABL/files/11391416/plugin_SmartABL.log)

**Comment by scmanjarrez** [comment]
Oh no, you misconfigured it. You have to put `G29, C108` in `ABL custom gcode`.
> `Trigger custom gcode` is intented for macros, or non standard default gcodes.

**Comment by AndyShap2020** [comment]
DOH! I’ll put G29, M500, C108 in Custom ABL.  I’ll let you know how it goes once I get to my next print.

_______________________________________________________________

Andy Shapiro, Owner
AS Consulting  (Networking, Hardware, Software & Training)
P.O. Box 1728, Goleta, CA. 93116-1728
Voice: (805) 968-6366
email: ***@***.***
Web: www.asconsulting.com<http://www.asconsulting.com/>

**Comment by AndyShap2020** [comment]
Looks like it is working fine. It DID clear the screen it DID save the mesh!

Thank you!

**Comment by scmanjarrez** [comment]
Did it trigger multiple times?

**Comment by AndyShap2020** [comment]
No, all appears to be working great.
