### ISSUE TITLE
[Request] Bed Visualizer compatibility

### ISSUE THREAD

**Issue by morris2009** [scmanjarrez/OctoPrint-SmartABL#16]
### Is your feature request related to a problem? Please describe.

Currently, if SmartABL triggers a bedlevel after X days, the Bed Visualizer plugin doesn't pickup this new mesh because Bed Visualizer doesn't pick this up.

In the normal start Gcode for every print there is the code for doing a mesh, as well as a line with "@BEDLEVELVISUALIZER".
SmartABL is very good at catching the code for doing the new mesh and strip it when it isn't needed, but it leaves the @BEDLEVELVISUALIZER line.
This sets the bedlevelvisualizer in the mode that it thinks the printer is doing a bedlevel while it actually started with the print itself.
 

### Describe the solution you'd like

It would be great if SmartABL could also send a "@BEDLEVELVISUALIZER"  in the Gcode. This would have bed visualizer pick-up this new mesh and display it.

And/or if in the normal GCODE the @BEDLEVELVISUALIZER line is there and it decides no bedlevel is needed, then also strip this line from the gcode.

**Comment by scmanjarrez** [comment]
You can configure the plugin to send this gcode and ignore it when found in *.gcode files. 
1. Enable `ABL custom gcode(s)` and set it to `G29, @BEDLEVELVISUALIZER`
2. Enable `Ignore gcode(s)` and set it to `@BEDLEVELVISUALIZER`

**Comment by scmanjarrez** [comment]
Hey, any update on this? Did the suggestion work for you?

**Comment by avavibes** [comment]
I believe this is actually a problem on the Bed level visualizer side.

**Comment by scmanjarrez** [comment]
Can you explain? Anyway, you can trigger that function just by sending the command as instructed above. I checked that SABL sent the command, not that BLV triggered tho (tested on virtual printer, so I don't have access to real mesh)

**Comment by avavibes** [comment]
The commands get sent, but ABL Visualizer doesn't actually observe them unless you press the button (In the visualizer) first, which is when it sends its own gcode.

**Comment by scmanjarrez** [comment]
Ok, I've talked with jneilliii, can you test with these steps?

1. Enable `ABL custom gcode(s)` and set it to `@BEDLEVELVISUALIZER, G29`
2. Enable `Ignore gcode(s)` and set it to `@BEDLEVELVISUALIZER`

Bear in mind that `@BEDLEVELVISUALIZER` should be sent before `G29` in order to work

**Comment by avavibes** [comment]
I tested that, as well as just sending `@ BEDLEVELVISUALIZER` in the terminal, and neither worked (Also, to get the data back, it needs to be `G29 T`)

**Comment by scmanjarrez** [comment]
I have tested it myself and works as expected. Are you using Marlin? The BEDLEVELVISUALIZER should be right after "at", i.e. `@BEDLEVELVISUALIZER`

This is config:
![image](https://github.com/scmanjarrez/OctoPrint-SmartABL/assets/9284124/24422858-ac95-445d-a6da-c20e74c92478)

![image](https://github.com/scmanjarrez/OctoPrint-SmartABL/assets/9284124/64389e2d-7f90-4ecb-bf10-975d74cdc4e8)


(Ignore my command, I'm using Klipper, so I had to use a different command)

If you're using Marlin, you should use `G29 T`: `@BEDLEVELVISUALIZER, G29 T`

If you use different firmware, check his repository, [he has gcode examples for different firmwares](https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/blob/master/wiki/gcode-examples.md)

**Comment by avavibes** [comment]
That's strange, somewhere when I was finding the visualizer gcode it said you needed the space after the @. I'm mid-print, but I'll test that as soon as its done (1h). Sorry for the trouble.

**Comment by avavibes** [comment]
It works perfectly, sorry for the trouble.

**Comment by morris2009** [comment]
I am sorry for the late reply.
With the suggestion of triggering on G29 and replacing it with @BEDLEVELVISUALIZER, G29 T;
it does what i want it to do, so that works!  tnx!!
Had some issues getting it to work in the beginning, not sure why, but now it does.
