### ISSUE TITLE
[Request] Reset smartabl when bed leveling is run not through a file. 

### ISSUE THREAD

**Issue by avavibes** [scmanjarrez/OctoPrint-SmartABL#17]
### Is your feature request related to a problem? Please describe.

When I run a bed level visualization with Bed Visualizer, it doesn't reset the counter on smartabl. 

### Describe the solution you'd like

It would be nice if SmartABL would detect the g29 being sent to the printer, or even had a macro that would reset the counter. (In such a way that the macro could be added to the bed level visualizer level gcode)

### Describe alternatives you've considered

It would work fine if there were just a button to reset it. Possibly, if you click on the middle area that shows the count of when the next abl will be run, giving a popup to reset it.

**Comment by scmanjarrez** [comment]
What do you think about a command you can send in terminal or gcode, like @SMARTABLRESET? Does it meet your request?

**Comment by BCurbs** [comment]
Yes, that would be perfect!

**Comment by avavibes** [comment]
That would be perfect!

**Comment by scmanjarrez** [comment]
Implemented in https://github.com/scmanjarrez/OctoPrint-SmartABL/releases/tag/1.2.0. Will be available through package updater in a few hours, depending on your settings.
